### ISSUE TITLE
PostgreSQL 17 pg_dump not found in make catalog backup script

### ISSUE THREAD

**Issue by FerencIstvan** [bacularis/bacularis-docker#10]
Dear @ganiuszka ,

I have pulled bacularis/bacularis-standalone:5.0.0-alpine, and the default catalog backup job failed with the following error:

`build-3-21-x86_64-dir JobId 90: BeforeJob: /etc/bacula/scripts/make_catalog_backup: exec: line 92: /usr/libexec/postgresql16/pg_dump: not found`

It is because of the new Postgre version. The bin directory is changed to /usr/libexec/postgresql**17** 
I have changed my scripts, and the catalog backup is fine now, but i did not checked full compatibility. 

Thank you for your efforts!

**Comment by ganiuszka** [comment]
Hello @FerencIstvan

Thank you for reporting this problem to us.

You are right that it is because of new version of PostgreSQL.

I fixed it. The fix will be available in Bacularis Docker images with the next version.

Best regards,
Marcin Haba (gani)

**Comment by gamedev-mjota** [comment]
Greetings and salutations, Marcinie @ganiuszka 

I've just experienced the same problem using the latest `bacula-standalone:latest` image. I have corrected myself the path to the binaries in `/etc/bacula/scripts/make_catalog_backup` inside the container while the container is running but until the image will be updated I will have to update the file every time the container will restart. When we can expect this fix to be pushed live?

Best Regards,
Darjusz

**Comment by ganiuszka** [comment]
Hello Darjuszu @gamedev-mjota

Thank you for reporting this problem. At the moment I checked it with fresh ``bacularis-standalone:latest`` image from DockerHub. Everything looks fine. I was not able to reproduce it. The fix is also visible in that project.

Could I ask you about making sure that you use this Bacularis image ``5.2.0``?

https://hub.docker.com/layers/bacularis/bacularis-standalone/latest/images/sha256-b3effb03503de255cdf603e9ef6f4c3acb95f31deec44fe8084eec733bd6b741

Thanks in advance for letting us know.

Best regards,
Marcin Haba (gani)

**Comment by ganiuszka** [comment]
Could you also check inside the container these two commands output?

```
# ls -l /usr/libexec/postgresql
```
```
# ls -l /usr/libexec/postgresql/
```
Thanks.

**Comment by gamedev-mjota** [comment]
Hey, thanks for taking the time to help with diagnosis of this whole issue. 
This is my docker-compose (volume parts skipped for brevity): 

```
services:
  bacularis:
    container_name: bacularis
    image: bacularis/bacularis-standalone:latest
    ports:
      - 9097:9097
    volumes:
      - bacula-config:/etc/bacula
      - bacula-db:/var/lib/postgresql/data
      - bacula-working:/var/lib/bacula
      - bacularis-api-config:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Config
      - bacularis-api-logs:/var/www/bacularis/protected/vendor/bacularis/bacularis-api/API/Logs
      - bacularis-web-config:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Config
      - bacularis-web-logs:/var/www/bacularis/protected/vendor/bacularis/bacularis-web/Web/Logs
      - bacularis-web-working:/var/www/bacularis/protected/vendor/bacularis/bacularis-common/Common/Working
      - bacula-storage:/opt/bacula-storage
    restart: unless-stopped
    env_file: .env
```

My portainer instance shows that the image being used in the container has the following hash: `sha256:f18f3a85f57a919f40c696d53733507b28b8638a2ecc2a6d1c271e248d72016d`

The outputs of the two commands are, accordingly: 

```
18d37bb3b298:/# ls -l /usr/libexec/postgresql
lrwxrwxrwx    1 root     root            12 May  8 07:19 /usr/libexec/postgresql -> postgresql17
```

and 

```
18d37bb3b298:/# ls -l /usr/libexec/postgresql/
total 14424
-rw-r--r--    1 root     root             3 Feb 21 16:34 PG_VERSION
-rwxr-xr-x    1 root     root         92504 Feb 21 16:34 clusterdb
-rwxr-xr-x    1 root     root         92728 Feb 21 16:34 createdb
-rwxr-xr-x    1 root     root         93048 Feb 21 16:34 createuser
-rwxr-xr-x    1 root     root         88344 Feb 21 16:34 dropdb
-rwxr-xr-x    1 root     root         88280 Feb 21 16:34 dropuser
-rwxr-xr-x    1 root     root        175624 Feb 21 16:34 initdb
-rwxr-xr-x    1 root     root         51624 Feb 21 16:34 oid2name
-rwxr-xr-x    1 root     root        117880 Feb 21 16:34 pg_amcheck
-rwxr-xr-x    1 root     root         47176 Feb 21 16:34 pg_archivecleanup
-rwxr-xr-x    1 root     root        183408 Feb 21 16:34 pg_basebackup
-rwxr-xr-x    1 root     root         80128 Feb 21 16:34 pg_checksums
-rwxr-xr-x    1 root     root        154160 Feb 21 16:34 pg_combinebackup
-rwxr-xr-x    1 root     root         46992 Feb 21 16:34 pg_config
-rwxr-xr-x    1 root     root         63488 Feb 21 16:34 pg_controldata
-rwxr-xr-x    1 root     root        121296 Feb 21 16:34 pg_createsubscriber
-rwxr-xr-x    1 root     root         76096 Feb 21 16:34 pg_ctl
-rwxr-xr-x    1 root     root        471192 Feb 21 16:34 pg_dump
-rwxr-xr-x    1 root     root        138688 Feb 21 16:34 pg_dumpall
-rwxr-xr-x    1 root     root         88216 Feb 21 16:34 pg_isready
-rwxr-xr-x    1 root     root        109144 Feb 21 16:34 pg_receivewal
-rwxr-xr-x    1 root     root        109248 Feb 21 16:34 pg_recvlogical
-rwxr-xr-x    1 root     root         72032 Feb 21 16:34 pg_resetwal
-rwxr-xr-x    1 root     root        236920 Feb 21 16:34 pg_restore
-rwxr-xr-x    1 root     root        178608 Feb 21 16:34 pg_rewind
-rwxr-xr-x    1 root     root         51216 Feb 21 16:34 pg_test_fsync
-rwxr-xr-x    1 root     root         42984 Feb 21 16:34 pg_test_timing
-rwxr-xr-x    1 root     root        195752 Feb 21 16:34 pg_upgrade
-rwxr-xr-x    1 root     root        109008 Feb 21 16:34 pg_verifybackup
-rwxr-xr-x    1 root     root        121376 Feb 21 16:34 pg_waldump
-rwxr-xr-x    1 root     root         71696 Feb 21 16:34 pg_walsummary
-rwxr-xr-x    1 root     root        216600 Feb 21 16:34 pgbench
-rwxr-xr-x    1 root     root       9986048 Feb 21 16:34 postgres
-rwxr-xr-x    1 root     root        691320 Feb 21 16:34 psql
-rwxr-xr-x    1 root     root         96792 Feb 21 16:34 reindexdb
-rwxr-xr-x    1 root     root        105400 Feb 21 16:34 vacuumdb
-rwxr-xr-x    1 root     root         47368 Feb 21 16:34 vacuumlo
```

**Comment by ganiuszka** [comment]
Hello Darjusz @gamedev-mjota,

Thanks for providing all details. Hmm, this is interesting case because all these outputs seem to be correct.

If you need to adapt the path in ``make_catalog_backup`` script, as you wrote, it can mean that in the container you have the original script for catalog backup, not fixed.

I don't know why in your container is original make catalog backup script. Maybe this checking inside fresh container can give us a bit more light:

```
grep postgres /etc/bacula/scripts/make_catalog_backup
```

```
stat /etc/bacula/scripts/make_catalog_backup
```

What are the outputs? Thanks for providing them.

At the end could I ask you about providing the exact error message from the Bacula job log? Please provide it even if this looks the same as in this error message in this issue. Maybe we can find something there. Sometimes little details make big problems :-)

Best regards,
Marcin Haba (gani)

**Comment by gamedev-mjota** [comment]
I think I figured out what the issue was. Because of the container volumes/mounts being bound to a physical path the files weren't updated along with the image update. After I deleted the old files and started from scratch with mounts so far no errors in the default jobs. 
My bad - I'm still all new to bacula and bacularis

**Comment by ganiuszka** [comment]
Hi @gamedev-mjota,

Great to hear that you found the reason of the problem. I think you found an interesting case because in Bacularis container images the Bacula configuration files are in ``/etc/bacula`` and Bacula scripts are in ``/etc/bacula/scripts``. So it is not easy to provide volume mount for ``/etc/bacula`` but not for ``/etc/bacula/scripts`` because mounts usually work with directories, not with files.

It looks that users starting from Bacularis ``5.2.0`` will not experience this issue. But users, who use volume bind to ``/etc/bacula`` on versions lower than ``5.2.0`` will experience it. For this case I think we will keep it as it is, but we need to find a procedure for changes in ``/etc/bacula/scripts/`` in the future.

Best regards,
Marcin Haba (gani)
